config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'hello_world', to: 'hello_world#index'
  get 'welcome/index'
  get 'users/login'
  get 'users/search'
  post 'users/login'
  post 'users/checkLogin'
  post 'users/search'
  root 'welcome#index'

  resources :users
  resources :signup
  resources :sessions
end

app/models/account.rb
class Account < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    def self.validate_user(username, password)
    	if username.nil?
    		return nil
    	end
		record = Account.find_by email: username
		puts "Mai aaya tha"
        record
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :_id, uniqueness: true
  searchable do
    text :headline, :default_boost => 2
    text :web_url
  end
end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	validates :name,  presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }

    def self.validate_user(username, password)
    	if username.nil?
    		return nil
    	end
		record = User.find_by email: username
		puts "Mai aaya tha"
        record
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :set_cache_headers

  #This method checks if we have a user signed in
  def login_required
    if !logged_in?
      flash[:notice] = "Log in to edit or delete your post"
      redirect_to welcome_index_path
    else
      flash[:notice] = "Alerting you to the monkey on your car!"
    end
  end

  def logged_in?
    !!current_user
  end

  helper_method :logged_in?

  #This method gives us details about our user
  def current_user
    if session[:user_id]
      @current_user = Account.find(session[:user_id])
      @current_user
    else
      false
    end
  end

  helper_method :current_user

  private

  def set_cache_headers
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    skip_before_action :verify_authenticity_token
	  def new
	    @user = Account.new
  	end

  	def create
    	user = Account.find_by_email(params[:email])
  		if user && user.authenticate(params[:password])
    		session[:user_id] = user.id
    		redirect_to root_path, :notice => "Welcome back, #{user.email}"
  		else
    		flash_now!(:error)
    		render "new"
  		end
  	end

  	def destroy
    	session[:user_id] = nil
      puts "session destroyed, user logged out"
    	redirect_to welcome_index_path
  	end

  	private
    	def login(user)
      		session[:user_id] = nil
    	end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
	def new
  	end

  	def create
	    @account = Account.new(account_params)
	    # binding.pry
	    if @account.save
	      	session[:account_id] = @account.id
	      	
	      	redirect_to signup_index_url
	    else
	    	flash_now!(:error)
	      	render :new
	    end
  	end

  	private

  	def account_params
    	params.require(:account).permit(:name, :email, :password)
  	end
end

app/controllers/users_controller.rb
require 'json'
require 'will_paginate/array'
require 'rsolr'
require 'fetch_api_data'
class UsersController < ApplicationController

	include GetDataFromAPI
	include UsersHelper

	before_action :login_required, only: [:show]

	def login
		@user = Account.new
	end

	def checkLogin
	    @username = params[:account][:email]
	    @password = params[:account][:password]
	    @user_exists = Account.validate_user(@username, @password) #check if user exists
	    puts @username, @password, @user_exists
	    if @user_exists
	      	puts "user exists"
	      	session[:user_id] = @user_exists.id
	      	redirect_to user_url(:id => @user_exists.id, :username => @username), :flash => :success
	    else
	    	flash_now!(:error)
	      puts "user does not exist"
	    end
	end

	def show
			if !is_number(params[:id]) || params[:id].nil?
				params[:id] = session[:user_id].to_s
				puts "after change:", params[:id]
			end
			@result = GetDataFromAPI.fetchData
			@username = params[:username]
	    if params[:user]
	      	@user = params[:user]
			else
					@user = Account.find(params[:id])
	    end
			@username = @user["name"]
	end

	def search
		puts "searching for term: ", params[:query]
		if !params[:query].blank?
			# Solr search on Article model
	    @searched = Article.search do
	      keywords(params[:query])
	    end

			session[:search_item] = @searched.results
			# puts "class is:", @searched.class
			# puts @searched.results.to_json
			render :json => {:art_search => @searched.results.to_json}
			# respond_to do |format|
			#   format.json  { render :json => {:articles_searched => @searched.results.to_json}}
			# end
			# redirect_to user_url(:id => session[:user_id], :searched => params[:query])
		else
			redirect_to user_url(:id => session[:user_id])
  	end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	  	if logged_in?
	  		flash[:success] = "You are already in!"
	  		record = Account.find(session[:user_id])
	      	redirect_to user_url(:id => session[:user_id], :username => record.name)
	    else
	    	flash[:notice] = "Alerting you to the monkey on your car!"
	    end
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def bootstrap_class_for(flash_type)
	  case flash_type
	  when "success"
	    "alert-success"   # Green
	  when "error"
	    "alert-danger"    # Red
	  when "alert"
	    "alert-warning"   # Yellow
	  when "notice"
	    "alert-info"      # Blue
	  else
	    flash_type.to_s
	  end
	end

	def fading_flash_notice
	    # note: you must have a div with id='notices' or rename the div appended to below with your element which
	    # is the container for the flash messages
	    return '' if !flash[:notice]
	    notice_id = rand.to_s.gsub(/\./, '')
	    notice = <<-EOF
	      $('#notices').append("<div id='#{notice_id}' class='flash_notice'>#{flash[:notice]}</div>");
	      $("##{notice_id}").fadeOut(5000);
	    EOF
	    notice.html_safe
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def is_number(str)
    true if Float(str) rescue false
  end

  module_function :is_number
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShahidRailsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <%= message %>
  </div>
<% end %>

app/views/signup/index.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to welcome_index_path, :class => 'navbar-brand' do %>
          RailsApp
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="mainNavBar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact Us</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to users_login_path, :class => 'button white' do %>
            <span class="glyphicon glyphicon-log-in" id="span"></span>Login
        <% end %></li>
          <!-- <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li> -->
      </ul>
  </div>
  </div>
</nav>
<div class="container">  
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6" style="margin-top: 100px">
      <div class="panel panel-default">
        <div class="panel-heading">
          Make an account
        </div>
        <div class="panel-body">
          <%= bootstrap_form_for :account do |f| %>
            <%= f.text_field :name, class: "input-lg" %>
            <%= f.email_field :email, class: "input-lg" %>
            <%= f.password_field :password, class: "input-lg" %>
            <%= f.submit "Create Now!", class: "btn btn-block btn-lg btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/login.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <%= link_to welcome_index_path, :class => 'navbar-brand' do %>
          RailsApp
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="mainNavBar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact Us</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to signup_index_path, :class => 'button white' do %>
          <span class="glyphicon glyphicon-user" id="span"></span>Signup
        <% end %></li>
      </ul>
    </div>
  </div>
</nav>
<%= render partial: "shared/flash_messages", flash: flash %> 
<div class="container">  
  <div class="row">
    <div class="col-sm-offset-3 col-sm-6" style="margin-top: 100px">
      <div class="panel panel-default">
        <div class="panel-heading">
          <span class="glyphicon glyphicon-user"></span>
          Login to your account
        </div>
        <div class="panel-body">
          <%= bootstrap_form_for(@user, :url => {:controller => 'users', :action => 'checkLogin'}) do |f| %>
              <%= f.text_field :email, class: "input-lg" %> </p>
              <%= f.password_field :password, class: "input-lg" %></p>
              <%= f.submit :Login , class: "btn btn-block btn-lg btn-primary" %> 
          <div class = "btn-group">
            <%= link_to( "Cancel", :action => "index", :controller => "welcome",  :class => "btn btn-success align-center") %>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to your Profile!</title>
  <% if flash[:notice] %>
    <script language='javascript'>
      $(document).ready(function() {
        <%= fading_flash_notice %>
      });
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDVZkosKzZQFIhnKS4HHLBZbzueCxbe9OM"></script>
  <% end %>
</head>
<script>
$(function() {
   $('.alert').delay(500).fadeIn('normal', function() {
      $(this).delay(2500).fadeOut();
   });
});
</script>
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to welcome_index_path, :class => 'navbar-brand' do %>
            RailsApp
        <% end %>
      </div>
      <div class="collapse navbar-collapse" id="mainNavBar">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Home</a></li>
          <li><a href="#">About</a></li>
          <li><a href="#">Contact Us</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to user_url, :class => 'button white' do %>
              <span class="glyphicon glyphicon-user" id="span"></span>Welcome <%= @username %>!
          <% end %></li>
          <li>
            <%= link_to session_path, :class => 'button white' , :method => 'delete' do %>
                <span class="glyphicon glyphicon-log-out" id="span"></span>Logout
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div>
    <%= react_component('HelloMessage', {name: @username, nytdata: @result, searchPath: users_search_url}) %>
  </div>


</body>
</html>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Welcome to RailsApp!</title>
	<% if flash[:notice] %>
		<script language='javascript'>
			$(document).ready(function() {
				<%= fading_flash_notice %>
			});
		</script>
	<% end %>
</head>
<script>
$(function() {
   $('.alert').delay(500).fadeIn('normal', function() {
      $(this).delay(2500).fadeOut();
   });
});
</script>
<body>
	<nav class="navbar navbar-inverse navbar-fixed-top">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="#">RailsApp</a>
	    </div>
	    <div class="collapse navbar-collapse" id="mainNavBar">
		    <ul class="nav navbar-nav">
		      <li class="active"><a href="#">Home</a></li>
		      <li><a href="#">About</a></li>
		      <li><a href="#">Contact Us</a></li>
		    </ul>
		    <ul class="nav navbar-nav navbar-right">
		    	<li><%= link_to signup_index_path, :class => 'button white' do %>
				    <span class="glyphicon glyphicon-user" id="span"></span>Signup
				<% end %></li>
				<li><%= link_to users_login_path, :class => 'button white' do %>
				    <span class="glyphicon glyphicon-log-in" id="span"></span>Login
				<% end %></li>
		        <!-- <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li> -->
		    </ul>
		</div>
	  </div>
	</nav>
	<%= render partial: "shared/flash_messages", flash: flash %> 
	<div class="jumbotron text-center">
	  <h1>My Sample Rails App</h1>
	  <p>Resize this responsive page to see the effect!</p> 
	</div>
	<div class="container">  
	  <div class="row">
	    <div class="col-sm-12">
	      <h3 class="text-center">Shahid's First Rails React App</h3>
	      <img src="/Golden-Gate-Bridge.jpg" class="img-thumbnail" alt="Cinque Terre" width="1800" height="1080">
	    </div>
	</div>
</body>
</html>